# Generated by Django 6.0.5 on 2026-05-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
